In [1]:
import pandas as pd
import numpy as np

In [12]:
flags = pd.read_csv('Z:/Livro_Pandas/flags2.csv', sep='\t')
flags.columns

Index(['name', 'landmass', 'zone', 'area', 'population', 'language',
       'religion', 'bars', 'stripes', 'colours', 'red', 'green', 'blue',
       'gold', 'white', 'black', 'orange', 'mainhue', 'circles', 'crosses',
       'saltires', 'quarters', 'sunstars', 'crescent', 'triangle', 'icon',
       'animate', 'text', 'topleft', 'botright'],
      dtype='object')

In [26]:
print('Linhas: ', flags.shape[0])
print('Colunas: ', flags.shape[1])

Linhas:  194
Colunas:  30

In [18]:
flags[flags['green']==1]

,name,landmass,zone,area,population,language,religion,bars,stripes,colours,...,saltires,quarters,sunstars,crescent,triangle,icon,animate,text,topleft,botright
0,Afghanistan,5,1,648,16,10,2,0,3,5,...,0,0,1,0,0,1,0,0,black,green
2,Algeria,4,1,2388,20,8,2,2,0,3,...,0,0,1,1,0,0,0,0,green,white
14,Bangladesh,5,1,143,90,6,2,0,0,2,...,0,0,0,0,0,0,0,0,green,green
17,Belize,1,4,23,0,1,1,0,2,8,...,0,0,0,0,0,1,1,1,red,red
18,Benin,4,1,113,3,3,5,0,0,2,...,0,0,1,0,0,0,0,0,green,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,Vanuatu,6,2,15,0,6,1,0,0,4,...,0,0,0,0,1,0,1,0,black,green
187,Venezuela,2,4,912,15,2,0,0,3,7,...,0,0,7,0,0,1,1,0,gold,red
191,Zaire,4,2,905,28,10,5,0,0,4,...,0,0,0,0,0,1,1,0,green,green
192,Zambia,4,2,753,6,10,5,3,0,4,...,0,0,0,0,0,0,1,0,green,brown
193,Zimbabwe,4,2,391,8,10,5,0,7,5,...,0,0,1,0,1,1,1,0,green,green

In [19]:
print('head(): ')
print(flags.head())

head():
             name  landmass  zone  area  population  language  religion  bars  \
0     Afghanistan         5     1   648          16        10         2     0
1         Albania         3     1    29           3         6         6     0
2         Algeria         4     1  2388          20         8         2     2
3  American-Samoa         6     3     0           0         1         1     0
4         Andorra         3     1     0           0         6         0     3

   stripes  colours  ...  saltires  quarters  sunstars  crescent  triangle  \
0        3        5  ...         0         0         1         0         0
1        0        3  ...         0         0         1         0         0
2        0        3  ...         0         0         1         1         0
3        0        5  ...         0         0         0         0         1
4        0        3  ...         0         0         0         0         0

   icon  animate text  topleft  botright
0     1        0    0    black     green
1     0        1    0      red       red
2     0        0    0    green     white
3     1        1    0     blue       red
4     0        0    0     blue       red

[5 rows x 30 columns]

In [10]:
print('tail(): ')
print(flags.tail())

tail():
              name  landmass  zone  area  population  language  religion  \
189  Western-Samoa         6     3     3           0         1         1
190     Yugoslavia         3     1   256          22         6         6
191          Zaire         4     2   905          28        10         5
192         Zambia         4     2   753           6        10         5
193       Zimbabwe         4     2   391           8        10         5

     bars  stripes  colours  ...  saltires  quarters  sunstars  crescent  \
189     0        0        3  ...         0         1         5         0
190     0        3        4  ...         0         0         1         0
191     0        0        4  ...         0         0         0         0
192     3        0        4  ...         0         0         0         0
193     0        7        5  ...         0         0         1         0

     triangle  icon  animate text  topleft  botright
189         0     0        0    0     blue       red
190         0     0        0    0     blue       red
191         0     1        1    0    green     green
192         0     0        1    0    green     brown
193         1     1        1    0    green     green

[5 rows x 30 columns]

In [20]:
#separar as cores
verde = flags['green']
amarelo = flags['gold']
azul = flags['blue']
branco = flags['white']

soma = verde + amarelo + azul + branco

#gera vetor booleano com True para quem tem as 4 cores

tem_todas = soma == 4

#imprime os nomes dos paises com as quatro cores

print('paises com verde, amarelo, azul e branco: ')
print(flags[tem_todas.values]['name'])

paises com verde, amarelo, azul e branco:
17                       Belize
19                      Bermuda
23                       Brazil
24         British-Virgin-Isles
26                     Bulgaria
33               Cayman-Islands
34     Central-African-Republic
48                     Dominica
56           Falklands-Malvinas
57                         Fiji
71                         Guam
78                    Hong-Kong
116                  Montserrat
135                     Parguay
139                    Portugal
142                     Romania
151             Soloman-Islands
158                   St-Helena
161                  St-Vincent
176         Turks-Cocos-Islands
182             US-Virgin-Isles
187                   Venezuela
Name: name, dtype: object